site_name: My technical wiki
site_url: https://mclargo.github.io
site_author: Javier Gil
site_description: Mix of features, good practices, tools and utils useful in my professional environment

theme:
  name: readthedocs
  highlightjs: true
  use_directory_urls: true
  hljs_languages:
    - yaml
  locale: en
  prev_next_buttons_location: bottom
  titles_only: true

extra:
  version: 2025.06

extra_css:
  - assets/css/extra.css

plugins:
  - search

nav:
  - Architecture:
    - Architecture Decision Records: architecture/architecture-decision-record.md
    - Communication:
      - Adaptive Bitrate Streaming: architecture/communication/abs.md
      - Asynchronous Messaging: architecture/communication/asynchronous-messaging.md
      - Graphql: architecture/communication/graphql.md
      - gRPC: architecture/communication/grpc.md
      - REST: architecture/communication/rest.md
      - Webhooks: architecture/communication/webhooks.md
      - Websocket: architecture/communication/websocket.md
    - Microservices:
      - 101 Microservices: architecture/microservices/microservices.md
      - Aggregator Pattern: architecture/microservices/aggregator.md
      - Anti-Corruption Layer: architecture/microservices/anti-corruption-layer.md
      - API Gateway: architecture/microservices/api-gateway.md
      - Backend For Frontend: architecture/microservices/bff.md
      - Bulkhead Pattern: architecture/microservices/bulkhead.md
      - Circuit Breaker Pattern: architecture/microservices/circuit-breaker.md
      - Command Query Responsibility Segregation Pattern: architecture/microservices/cqrs.md
      - Database Per Microservice Pattern: architecture/microservices/database-per-service.md
      - Distributed Transactions Patterns: architecture/microservices/distributed-transaction-patterns.md
      - Event Driven: architecture/microservices/event-driven.md
      - Saga Pattern: architecture/microservices/saga-pattern.md
      - Service Mesh: architecture/microservices/service-mesh.md
      - Sidecar Pattern: architecture/microservices/sidecar.md
      - Strangler Fig Pattern: architecture/microservices/strangler-fig.md
    - Patterns:
      - Concurrency patterns: architecture/patterns/concurrency-patterns.md
      - Data Storage: architecture/patterns/data-storage.md
      - Database Patterns: architecture/patterns/database-patterns.md
      - Domain Driven Architecture: architecture/patterns/domain-driven.md
      - Design Patterns: architecture/patterns/design-patterns.md
      - Hexagonal Architecture: architecture/patterns/hexagonal-architecture.md
      - Monolithic Architecture: architecture/patterns/monolithic.md
      - Retry Mechanism: architecture/patterns/retry-mechanism.md
      - Solid Principles: architecture/patterns/solid.md
      - State Pattern: architecture/patterns/state-pattern.md
      - Vertical Slice: architecture/patterns/vertical-slice.md
  - DevOps:
    - Continuous Integration: devops/continuous-integration.md
    - Deployment Strategies: devops/deployment-strategies.md
    - Docker: devops/docker.md
    - Features Toggles: devops/features-toggles.md
    - Helm Charts: devops/helm.md
    - Kubernetes: devops/k8s.md
    - Load Shedding: devops/load-shedding.md
    - Observability: devops/observability.md
    - Serverless Computing: devops/serverless.md
    - Versioning: devops/versioning.md
  - Machine Learning:
    - Algorithms: machine-learning/algorithms.md
    - Deep Learning: machine-learning/deep-learning.md
    - Fundamentals: machine-learning/fundamentals.md
    - Input Data: machine-learning/input-data.md
    - Responsibilities: machine-learning/responsibilities.md
  - Programming:
    - Algorithm Complexity: programming/algorithm-complexity.md
    - Conventional Commits: programming/conventional-commits.md
    - Development Workflows: programming/development-workflows.md
    - Django: programming/django.md
    - FastApi: programming/fastapi.md
    - Flask: programming/flask.md
    - Golang: programming/golang.md
    - OpenAPI Specification: programming/openapi.md
    - Python: programming/python.md
    - SQLAlchemy: programming/sqlalchemy.md
    - Virtualenvs: programming/virtualenvs.md
  - Project Management:
    - C4 Model: project-management/c4-model.md
    - Diagram Flows: project-management/diagram-flows.md
    - Product Owner: project-management/product-owner.md
    - SCRUM: project-management/scrum.md
    - Technical Leader: project-management/tech-lead.md
    - Waterfall Methodology: project-management/waterfall-methodology.md
    - Work Remotely: project-management/work-remotely.md
  - Utils:
    - Authentication: utils/authentication.md
    - Cache: utils/cache.md
    - Daemon: utils/daemon.md
    - Database table indexes: utils/db-table-indexes.md
    - Databases: utils/databases.md
    - IDE: utils/ide.md
    - Proxy: utils/proxy.md
    - Regex: utils/regex.md
    - Runbooks: utils/runbooks.md
    - Scaling: utils/scaling.md
    - Supervisor: utils/supervisor.md
    - Task runner: utils/task-runner.md
    - Testing: utils/testing.md
    - Ubuntu: utils/ubuntu.md
    - Working Environment: utils/working-environment.md

copyright: Copyright &copy; 2025 <a href="https://github.com/McLargo">Javier Gil</a>.
